version: '3.8'

services:
  latex_builder:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UID: "${UID}"
        GID: "${GID}"
    volumes:
      - ./artifacts:/app/artifacts
    working_dir: /app
    user: "${UID}:${GID}"
    env_file:
      - .env
