name: Homework
on:
  push:
    branches:
      - main
      - dev
    tags:
      - v*
  pull_request:
    branches:
      - main

jobs:
  
  linter:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache Python Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-python-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-python-
      - name: Python Dependencies
        uses: ./.github/actions/common-steps
      - name: Run Linter
        run: uv run ruff check . --no-cache

  mypy:
    name: MyPy [Optional]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache Python Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-python-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-python-
      - name: Python Dependencies
        uses: ./.github/actions/common-steps
      - name: Type Checker [Optional]
        run: uv run mypy src

  tests:
    name: Pytest
    needs: [linter]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache Python Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-python-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-python-
      - name: Python Dependencies
        uses: ./.github/actions/common-steps
      - name: Install TeX
        run: |
          sudo apt update
          sudo apt install -y -qq texlive-latex-base
      - name: Run tests
        run: uv run pytest tests -s -vv --color=yes
